baseurl = "http://pelle.io/"
languageCode = "en-us"
title = "pelle.io"
canonifyurls = true
theme = "beautifulhugo"

[Params]
  logo = "img/avatar-icon.png"
  subtitle = ""

[Author]
  name = "Christian Pelster"
  email = "pelle@pelle.io"
  github = "pellepelster"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
