name = "pelle.io"
license = "MIT"
min_version = 0.48

[author]
name = "pelle"
homepage = "https://pelle.io"

[original]
author = "BeautifulHugo"
homepage = "https://github.com/halogenica/Hugo-BeautifulHugo"
repo = "https://github.com/halogenica/Hugo-BeautifulHugo"
