baseURL = "http://pelle.io/"
languageCode = "en-us"
title = "pelle.io"
theme = "hallo"

[Author]
    name = "pelle"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/pellepelster"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:pelle@pelle.io"        