baseURL = "http://pelle.io/"
languageCode = "en-us"
title = "pelle.io"
theme = "pelle.io"

[Params]
  logo = "img/portrait.jpg"
  selfHosted = true

[Author]
    name = "pelle"
    email = "pelle@pelle.io"
    github = "pellepelster"
    