---
groups:
  - direction: horizontal
    groups:
      - name: Operations, Deployment & Lifecycle
        direction: vertical
        components:
          - name: Playbooks
            logo: logos/list-ol.svg
            info: |
              Playbooks are a crucial part of every deployment and provide detailed procedures for
              scenarios like disaster recovery or secret rotation during emergencies. They also
              provide information for general operations and maintenance tasks to the operations team
            selected: How I can prepare my on-call team with appropriate playbooks for operational challenges
          - name: Fire Drills
            logo: logos/fire-extinguisher.svg
            info: |
              Regular exercises ensure that crucial steps that are seldom used still work as
              intended, and that developers are comfortable with executing them
            selected: |
              How to use simulated outages and service degradations to train my on-call team and spread
              operational confidence
          - name: Support
            logo: logos/phone.svg
            info: |
              In the event of critical errors, such as larger outages, crashing services or data loss,
              German and English emergency support is available via email, phone, or chat
            selected: |
              How to get live-assistance when services are interrupted.
          - name: Environments
            logo: logos/layer-group.svg
            info: |
              Multi-environment support is a first-class citizen. It can be used to support
              your application lifecycle and to provide different test environments
            selected: |
              How to implement multiple environments to support different development stages
          - name: Bootstrapping
            logo: logos/rocket.svg
            info: |
              Deletion and bootstrapping of environments is systematically tested to ensure
              there are no hidden cyclic dependencies in the infrastructure setup. This method
              also confirms that the code which is only executed during the initial setup
              continues to function correctly
            selected: |
              How to ensure the my infrastructure is always black-start ready so I can deal with provider outages
          - name: DX
            logo: logos/terminal.svg
            info: |
              A strong focus on the developer experience helps to tame the amount and diversity and tooling needed
              to deploy applications and infrastructure. A good consistent CLI can make crucial tasks safer to
              execute and helps to ease day-to-day platform operations
            selected: |
              How to improve day-to-day operations and make critical tasks safe to execute
          - name: Updates
            logo: logos/arrows-rotate.svg
            info: |
              Regular operating system and software updates are essential to ensure the latest security fixes
              are always applied, and current vulnerabilities are patched promptly
            selected: |
              How to keep my infrastructure and software stack always up-to-date

          - name: Disaster Recovery
            logo: logos/fire.svg
            info: |
              Restoring environments from backups is tested regularly and is included in both
              the playbooks and developer briefings. All components are designed in a way, that
              the entire environment can be destroyed at any time, and then fully rebuilt from
              the backups.
            selected: |
              How to build and test environments that survive outages or attacks and can be
              restored from external backups

      - direction: vertical
        groups:
          - name: Logging & Monitoring
            direction: vertical
            info: |
              A solid log and metrics collection and visualization strategy is irreplaceable to
              ensure safe and efficient operations and enable efficient debugging of problems
            selected: |
              How to implement solid monitoring with
            components:
              - name: Grafana
                logo: logos/grafana.svg
              - name: Elastic.co
                logo: logos/elastic.svg
              - name: Datadog
                logo: logos/elastic.svg
              - name: unknown_logging
                type: unknown
                logo: logos/person-circle-question.svg
                selected: |
                  How to choose the right monitoring solution for my system landscape

          - name: Security & Data Safety
            direction: vertical
            components:
              - name: Encryption
                logo: logos/lock.svg
                info: |
                  All off-cloud backups are encrypted by default. Data at rest and in transit
                  is protected using industry-standard encryption practices
                selected: |
                  How to protect your data using industry-standard encryption practices
              - name: Secret Rotation
                logo: logos/key.svg
                info: |
                  Credentials and secrets are auto-generated with strong entropy and stored in
                  dedicated secret providers. Rotation procedures are documented in playbooks
                  and regularly exercised in fire drills
                selected: |
                  How to implement safe and regular secret rotation
              - name: CVE Scanning
                logo: logos/shield-halved.svg
                info: |
                  Automated CVE scanning is performed using Software Bill of Materials (SBOM)
                  analysis, providing continuous visibility into known vulnerabilities across
                  all components in the stack
                selected: |
                  How to safeguard my environments against supply chain attacks
              - name: IAM / IDP
                logo: logos/user-shield.svg
                info: |
                  A central identity and access management solution enables enabling fine-grained
                  access control and centralised authentication across all services
                selected: |
                  How to implement centralized identity and access management to protect my services

      - direction: vertical
        groups:
          - name: Hosting
            direction: horizontal
            info: |
              I have a experience of hosting a wide range of standard open and non-open source software
            selected: |
              I need help to host
            components:
              - name: Keycloak
                logo: logos/keycloak.svg
              - name: HashiCorp Vault
                logo: logos/vault.svg
              - name: PostgreSQL
                logo: logos/postgresql.svg
              - name: unknown_hosting
                type: unknown
                logo: logos/person-circle-question.svg
                selected: |
                  I need support hosting applications


          - name: Hosting
            direction: horizontal
            groups:
              - name: Hyperscaler
                direction: horizontal
                info: |
                  The big three Hyperscaler offer an unmatched range of services and scalability, which
                  can come with a higher price and higher complexity.
                selected: |
                  How to cost-effective use
                components:
                  - name: AWS
                    logo: logos/aws.svg
                  - name: Azure
                    logo: logos/azure.svg
                  - name: GCP
                    logo: logos/gcp.svg
              - name: EU Clouds
                direction: horizontal
                info: |
                  For smaller environments, one of the European alternatives can be a cost-effective solution with giving
                  up too much operational comfort when compared to the hyoerscalers.
                selected: |
                  How to deploy applications to
                components:
                  - name: Hetzner
                    logo: logos/hetzner.svg
                    selected: Neque porro quisquam est qui dolorem ipsum quia dolor sit.
                  - name: Scaleway
                    logo: logos/scaleway.svg
                    selected: Quis autem vel eum iure reprehenderit qui in ea voluptate.
              - name: Bare-metal
                direction: horizontal
                info: |
                  Bare-Metal solutions need more attention and management, but can be super cost-effective especially
                  for I/O intensive database workloads, or when raw compute and storage is needed.
                selected: |
                  How to implement bare-metal hosting solutions on
                components:
                  - name: OVH
                    logo: logos/ovh.svg
                    selected: Neque porro quisquam est qui dolorem ipsum quia dolor sit.
                  - name: Contabo
                    logo: logos/contabo.svg
                    selected: Quis autem vel eum iure reprehenderit qui in ea voluptate.
              - name: unknown_hosting
                type: unknown
                selected: |
                  How to choose the right hosting solution for my needs

          - name: Infrastructure as Code
            direction: horizontal
            info: |
              Having built infrastructures in a broad selection of different IaC tools, I can guide you through the
              jungle and select the best solution for your environment.
            selected: |
              How to implement robust and reproducible infrastructures using
            components:
              - name: Terraform
                logo: logos/terraform.svg
              - name: OpenTofu
                logo: logos/opentofu.svg
              - name: Ansible
                logo: logos/ansible.svg
              - name: AWS CDK
                logo: logos/aws-cdk.png
              - name: Pulumi
                logo: logos/pulumi.svg
              - name: unknown_iac
                type: unknown
                logo: logos/person-circle-question.svg
                selected: |
                  How to figure out which IaC tools are right for me

          - name: CI/CD
            direction: horizontal
            info: |
              I have worked with all major CI/CD Platforms and helped to implement robust build, test and deployment
              pipelines, enabling end-to-end visibility for deployed artifacts and infrastructure
            selected: |
              How to implement robust CI/CD pipelines with
            components:
              - name: GitHub
                logo: logos/github.svg
              - name: GitLab
                logo: logos/gitlab.svg
              - name: Jenkins
                logo: logos/jenkins.svg
              - name: ArgoCD
                logo: logos/argo.svg
              - name: CircleCI
                logo: logos/circleci.svg
              - name: TeamCity
                logo: logos/teamcity.svg
              - name: Forgejo
                logo: logos/forgejo.svg
              - name: unknown_cicd
                type: unknown
                logo: logos/person-circle-question.svg
                selected: |
                  How to choose the right CI/CD solution for my needs
                info: |
                  If you are unsure which solution is the right one for you I can guide you through the selection process based on your requirements

          - name: Networking
            direction: horizontal
            selected: |
              How to secure cross service and/or cross cloud communication with
            components:
              - name: WireGuard
                logo: logos/wireguard.svg
              - name: OpenVPN
                logo: logos/openvpn.svg
              - name: mTLS
                logo: logos/certificate.svg
              - name: unknown_networking
                type: unknown
                logo: logos/person-circle-question.svg
                selected: |
                  How to choose the right networking for my multi-cloud deployment
                info: |
                  If you are unsure which solution is the right one for you I can guide you through the selection process based on your requirements
