baseURL = "https://solidblocks.de/"
languageCode = "en"
title = "solidblocks.de"
theme = "pelle.io"

[Params]
logo = "img/logo.png"
selfHosted = true
homeTitle = "solidblocks"
customCss = "solidblocks.css"

[Params.author]
name = "Christian 'Pelle' Pelster"
email = "contact@solidblocks.de"
github = "pellepelster/solidblocks"
phone = "+49 176 238 170 01"

[markup.goldmark.renderer]
unsafe = true

[languages]

[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2