baseURL = "https://solidblocks.de/"
languageCode = "en"
title = "solidblocks.de"
theme = "pelle.io"
defaultContentLanguageInSubdir = true

[Params]
selfHosted = true
logo = "img/logo.png"
customCss = "solidblocks.css"

[Params.author]
name = "Christian 'Pelle' Pelster"
email = "contact@solidblocks.de"
github = "pellepelster/solidblocks"
linkedin = "christian-pelster-017907133"
phone = "+49 176 238 170 01"

[markup.goldmark.renderer]
unsafe = true

[languages]

[languages.en]
languageName = "English"
weight = 1

[languages.en.params]
homeTitle = "Hello, I am Pelle"

[languages.de]
languageName = "Deutsch"
weight = 2

[languages.de.params]
homeTitle = "Hallo, ich bin Pelle"

[deployment]
[[deployment.targets]]
name = "blcks"
URL = "s3://pelle-solidblocks-de?endpoint=http://s3.blcks.de&region=blcks&use_path_style=true"