name: pelle.io

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      with:
        submodules: true

    - name: bootstrap
      run: ./do bootstrap

    - name: build
      run: ./do build

    - name: deploy
      env:
        S3_HOST: ${{ secrets.S3_HOST }}
        PELLE_IO_ACCESS_KEY: ${{ secrets.PELLE_IO_ACCESS_KEY }}
        PELLE_IO_SECRET_KEY: ${{ secrets.PELLE_IO_SECRET_KEY }}
        SOLIDBLOCKS_DE_ACCESS_KEY: ${{ secrets.SOLIDBLOCKS_DE_ACCESS_KEY }}
        SOLIDBLOCKS_DE_SECRET_KEY: ${{ secrets.SOLIDBLOCKS_DE_SECRET_KEY }}
      run: ./do deploy