name: pelle.io

permissions:
  packages: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: mise setup
        uses: jdx/mise-action@v4.0.1

      - name: login to GitHub container registry
        uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: install s3cmd
        run: sudo apt-get install -y s3cmd

      - name: build sites
        run: mise sites:build

      - name: build contact docker image
        run: mise contact:docker:build

      - name: push contact docker image
        run: mise contact:docker:push

      - name: deploy sites
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
          PELLE_IO_ACCESS_KEY: ${{ secrets.PELLE_IO_ACCESS_KEY }}
          PELLE_IO_SECRET_KEY: ${{ secrets.PELLE_IO_SECRET_KEY }}
          SOLIDBLOCKS_DE_ACCESS_KEY: ${{ secrets.SOLIDBLOCKS_DE_ACCESS_KEY }}
          SOLIDBLOCKS_DE_SECRET_KEY: ${{ secrets.SOLIDBLOCKS_DE_SECRET_KEY }}
        run: mise sites:deploy